### ISSUE TITLE
Size flag doesn't seem to be working

### ISSUE THREAD

**Issue by mbigras** [tav/asciinema2gif#41] opened 2016-11-17 01:07 UTC
I'm able to adjust the size by giving asciinema.org the `size=big` option, shown here: https://asciinema.org/api/asciicasts/5ljjg4iuybn8wpf5rk67m1e9z?size=big

However, when I tried:

`asciinema2gif --size big -o output_big.gif https://asciinema.org/api/asciicasts/5ljjg4iuybn8wpf5rk67m1e9z`

The size is still small. 

Am I missing something here?

Thanks for your help 😄

**Comment by wong2** [comment] 2016-11-17 04:05
@mbigras which version are you using? I'm getting the big one here (click to open in new tab):

![output_big](https://cloud.githubusercontent.com/assets/321947/20375987/00aefa80-acbe-11e6-8c8a-193a52ff1774.gif)

**Comment by mbigras** [comment] 2016-11-18 05:16
Hi @wong2 
I just checked the version through `brew list`, I think it's the most recent release 0.5

```
/usr/local/Cellar/asciinema2gif/0.5/bin/asciinema2gif
/usr/local/Cellar/asciinema2gif/0.5/libexec/bin/ (2 files)
```

I see the link will take you to a new tab where the font is bigger but is it possible to have the bigger font also in the gif that is shown via a markdown link?

In your attached gif the font still appears small to someone who is just viewing it without clicking on the link as shown:

![](https://www.dropbox.com/s/wfcsnv170e5wxi1/Screenshot%202016-11-17%2021.12.45.png?dl=1)

I'd like to use `asciinema2gif` to generate gifs for my readmes like at [mbigras/mb-fullstop](https://github.com/mbigras/mb-fullstop) but the font appears super small to someone who is just browsing through 🙁

**Comment by wong2** [comment] 2016-11-18 10:14
@mbigras ok, I understant it now. However, the size flag of `asciinema2gif` controls the total size of the resulting gif, while what you need is keepping the image size while increasing the font size, which is currently not possible by `asciinema2gif`, maybe you can try some gif editing tools to crop the generated gif from the left-top corner.

**Comment by wong2** [comment] 2016-11-18 10:19
@mbigras for example this one: http://ezgif.com/crop

**Comment by wong2** [comment] 2016-11-18 10:21
The result:

![ezgif com-3edfa5a7e4](https://cloud.githubusercontent.com/assets/321947/20426769/9e87c770-adbb-11e6-867a-d0d0850c855d.gif)

**Comment by wong2** [comment] 2016-11-18 10:21
since this is not a bug of `asciinema2gif` itself, I'll close this issue

**Closed as completed by wong2** 2016-11-18 10:21 UTC
